### ISSUE TITLE
Window corners not being rendered properly in some applications

### ISSUE THREAD

**Issue by berkiyo** [vinceliuice/stylish-gtk-theme#10]
Hi there,

Firstly, thank you for creating such a clean and beautiful theme! Recently, I have noticed that some applications have sharp corners or corners with grey pixels in the corner. Do you know what the cause is?

**Firefox, VirtualBox and programs that use similar GUI toolkits**
Here is what Firefox and some other programs look like. Although it isn't a big issue, it is a little annoying. Themes like Vertex, Arc and Adwaita don't have these issues.
![firefox](https://user-images.githubusercontent.com/38805550/40054819-79ace58c-5889-11e8-9e2f-07649c9a5015.png)

**GNOME Settings: Sharp Corners**
This one is annoying as it breaks the consistency with all the other applications but it isn't a deal-breaker. I've tested this theme and **Vimix** - both have sharp corners in gnome-settings.
![gnome-settings](https://user-images.githubusercontent.com/38805550/40055155-549f5d14-588a-11e8-93d1-7473ee761a05.png)

**Other GNOME applications seem to be fine**
GNOME Terminal and other applications seem to be fine and not affected by sharp/dark-pixel corners.
![gnome-terminal](https://user-images.githubusercontent.com/38805550/40055208-7a262f22-588a-11e8-8bb4-ca57aec1879b.png)

I'm running Fedora 28 with GNOME 3.28. Do you have a solution for this minor issue?

**Comment by vinceliuice** [comment]
Thanks! I'll fix this.

**Comment by bkdogan** [comment]
You have updated the theme but now the subtle curve is gone. Are there plans to bring it back? It looked really nice before.

**Comment by berkiyo** [comment]
Thanks for updating the theme so quickly! I see you got rid of the rounded corners and instead went with sharp corners. It is a shame that the rounded corners are gone but I guess the theme is more consistent now.

**Comment by vinceliuice** [comment]
FIxed now!
