### ISSUE TITLE
Issue with font color in mate panel (dark variant)

### ISSUE THREAD

**Issue by phocean** [vinceliuice/stylish-gtk-theme#11]
In mate-desktop, the font color panel is not suitable for the dark version : it is dark color on dark background.

The workaround consists in adding this in `.config/gtk-3.0/gtk.css`:

```
panel-toplevel.background.horizontal,
.mate-panel-menu-bar,
#clock-applet-button,
#clock-applet-button:hover  {
        color: white;
}

#tasklist-button {
        color: white;
}
```

It should be handled natively by the theme.

Thank you and awesome work, otherwise :-)

**Comment by vinceliuice** [comment]
Thanks
