### ISSUE TITLE
Minor glitch in indicator of Volume/Brightness

### ISSUE THREAD

**Issue by jeffshee** [vinceliuice/stylish-gtk-theme#13]
![stylish](https://user-images.githubusercontent.com/25530920/48197740-fda8ce00-e399-11e8-83f6-79901cdec3d8.png)
I believe the indicators (the bar as picture shown) of volume and brightness, are not themed properly. I'm sorry if they are by design, but they look quite different to earlier version. Currently using the latest version, as updated today.

**Comment by vinceliuice** [comment]
Fixed now
