### ISSUE TITLE
GTK2 - menu null separator

### ISSUE THREAD

**Issue by pkomur** [vinceliuice/stylish-gtk-theme#4]
Please change menu separator to line like in Vimix theme. 

Null separator
![stylish-sep](https://user-images.githubusercontent.com/11897534/34810509-17c59994-f69c-11e7-838c-01f5edb72bfc.png)

Line separator
![vimix-sep](https://user-images.githubusercontent.com/11897534/34810513-1e16aa90-f69c-11e7-9e61-df2d6f35b528.png)

**Comment by vinceliuice** [comment]
Add menu separator now

**Comment by pkomur** [comment]
Thanks.
