### ISSUE TITLE
GTK3 - Edit Text field issue

### ISSUE THREAD

**Issue by pkomur** [vinceliuice/stylish-gtk-theme#5]
Cannot enter any value in _Edit Text_ field on Top Bar (e.g. gedit print preview).
![pic1n](https://user-images.githubusercontent.com/11897534/35993059-7098c790-0d0c-11e8-9807-39e660db47a3.png)
In Azure theme is OK.
![pic2](https://user-images.githubusercontent.com/11897534/35993164-bca2dedc-0d0c-11e8-80a3-9b42c99c313e.png)

The same issue is in Vimix theme.

**Comment by vinceliuice** [comment]
I'm working on it, I'll try my best to fix this

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by pkomur** [comment]
Great job! Thanks.
