### ISSUE TITLE
Key repeat not working

### ISSUE THREAD

**Issue by coleifer** [vinceliuice/stylish-gtk-theme#6]
The keyboard does not seem to support key repeating when I am using this theme -- i.e. hold down a key and it only logs a single keypress, whereas I'd expect that after a short timeout, the key would repeat. Works fine with your other themes (matcha and abrus).

**Comment by vinceliuice** [comment]
I don't get it, you mean this theme have issues with keyboard?

**Comment by coleifer** [comment]
Yeah, if I put the cursor into the text-bar of Chrome, say, and hold down backspace it will only delete a single character. It's like the "repeat" isn't working. Xubuntu 17.10, if that helps.

**Comment by coleifer** [comment]
I noticed when updating the vimix theme a day or two ago that key-repeat seems to be broken with that theme as well. Perhaps you can identify what change caused this?

**Comment by vinceliuice** [comment]
You mean the earlier versions works well?

**Comment by coleifer** [comment]
Yep. Change happened maybe in the last week or so?

**Comment by coleifer** [comment]
Shoot, apparently I misspoke. I tried doing a git-bisect on vimix and apparently I was mistaken about it having worked recently. Sorry, disregard my earlier comment.

**Comment by coleifer** [comment]
I don't know if this helps, but Ultimate-Maia theme has this same issue (not yours, but might help you diagnose?).

Themes that work as expected:

* abrus
* matcha
* canta (very nice, btw)
* materia (not yours)

Hope that helps.

**Comment by vinceliuice** [comment]
May be there is something wrong with compilation tool : sassc, because I used ruby-sass for compilation tool, But more than two weeks ago I switch to sassc ( as some tool as materia using ) beacuse ruby-sassc have some unfixed bugs.

**Comment by vinceliuice** [comment]
And one thing that puzzle me is I still not find out the issues you described on my desktop, I tried hold down backspace and it can delete all characters I put in.

**Comment by coleifer** [comment]
I noticed in the README that this theme is based on "materia". On my laptop, "materia" is working correctly, while Vimix and Stylish (based on materia) have some underlying problem.

As I said, I rolled Vimix back to a commit from September, 2017 to see if an earlier version worked, and unfortunately the key repeat was broken back then too. I also tried manually toggling the key repeat settings in the settings manager.

Maybe it's the sass compiler but given that it was broken as far back as September of last year I doubt that's it?

> And one thing that puzzle me is I still not find out the issues you described on my desktop, I tried hold down backspace and it can delete all characters I put in.

I'm using Xubuntu 17.10. Might be related to some of the differences in the way xfce handles themes?

**Comment by vinceliuice** [comment]
Can you tell me does Canta works well too? Because Canta based on last version of materia theme ( I just finished Canta 5 days ago ) , but Vimix and Stylish are based on very earlier version of materia theme ( it was named Flat-plat that time )

**Comment by coleifer** [comment]
Yes, canta works correctly.

**Comment by vinceliuice** [comment]
Then this must be a bug left by an earlier version of materia theme, I'll check feedback informations of materia theme to find if There is some similar problem, maybe that'll help.

**Comment by coleifer** [comment]
I skimmed the pull requests and issues and nothing jumped out at me.

**Comment by coleifer** [comment]
Working for me on latest.
