### ISSUE TITLE
Severe slowdown on heavily populated iconview

### ISSUE THREAD

**Issue by M4he** [vinceliuice/stylish-gtk-theme#9]
### Issue Description

This GTK3 theme shows severe performance issues on heavily populated `iconview` views. Affected applications are for instance file managers like Nautilus or Nemo. They show heavy lags and delays in folders containing many (thousands) of thumbnail elements.

The issue is not happening with other popular GTK3 themes that aren't based on Materia, such as Adwaita or Arc for instance.

### Steps to Reproduce

1. You need to have a folder containing a huge amount of picture files
    - in my case it was a folder with around 2600 wallpapers*
2. Open up the folder in Nautilus in icon view, have thumbnails enabled
3. Open up another Nautilus window on any other folder
4. Switch focus between the windows

*note: reproducing this with simple mechanics seems to be tricky. I tried using a JPG with small file size and copying it 4000 times into the same folder. That did not trigger the issue. Seems like you need actually varying images.

##### Expected Outcome

- The window with the picture files should react normally

##### Actual Outcome

- The window with the picture files shows heavy delay (1 - 2 seconds) after being selected
   - a CPU usage spike can be observed after selecting (focusing) the window
   - clicks don't register correctly during the delay, scrolling does not react
   - animations (ripple effects etc.) in the file manager are very laggy during the delay
- Always happens after the window is focused again after being unfocused

### Root Cause

After some digging in the CSS code I seem to have identified the root cause of this.

It seems to be the `background-image` property in [the following lines](https://github.com/vinceliuice/stylish-gtk-theme/blob/760e3293f3f15b898ca271cf3c18214d81cd7e78/src/gtk-3.0/gtk.css#L3896):
```
row.activatable, .view, iconview, treeview.view header button, .budgie-menu button {
  transition: all 0.3s cubic-bezier(0, 0, 0.2, 1), background-color 0, color 0;
  box-shadow: inset 0 0 0 9999px alpha(currentColor, 0);
  background-image: radial-gradient(circle farthest-corner at center, alpha(currentColor, 0) 100%, transparent 0%), image(alpha(currentColor, 0));
}

row.activatable:hover, .view:hover, iconview:hover, treeview.view header button:hover, .budgie-menu button:hover {
  transition: none;
  box-shadow: inset 0 0 0 9999px transparent;
  background-image: radial-gradient(circle farthest-corner at center, alpha(currentColor, 0) 100%, transparent 0%), image(alpha(currentColor, 0));
  background-color: alpha(currentColor, 0.05);
}
```

When I remove the `background-image` lines, everything behaves correctly.

### System Information

- Theme version: current master (760e329)
- GTK+ 3 version: 3.22.11
- Distribution: Debian stretch 9.4
- Desktop: awesome v4.2 standalone + xsettingsd (no DE)
- GPU: Intel Haswell Integrated Graphics

### Addendum

- what is the `background-image` property actually used for anyway - from my interpretation it seems to draw a completely invisible (alpha = 0) area?
- this also affects your other Materia-derivative themes like Vimix
   - should I open an Issue there as well?
- oddly enough, the upstream theme (Materia) seems to have changed the code - the issue also applies to Materia but the fix shown above does not seem to apply anymore

**Comment by vinceliuice** [comment]
Thank you so much for describing the problem in detail. You have really helped me a lot. I will fix this bug (including vimix) according to the method you provided.

**Comment by M4he** [comment]
You are very welcome! Glad, I could be of help. Thank you for your hard work on those excellent GTK themes!
